[package]
name = "a7i-api"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
rcgen.workspace = true
salvo.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
